# default parameters for lane_filter/lane_filter_node

debug : True
predict_frequency: 30.0 # 30in Hz
lane_filter_histogram_configuration:
  # ADD PARAMETERS HERE
  mean_d_0: 0.0
  mean_phi_0: 0
  sigma_d_0: 0.3
  sigma_phi_0: 0.3
  delta_d: 0.01 #0.02
  delta_phi: 0.05 #0.1
  d_max: 0.12 #0.27 #0.3
  d_min:  -0.11 #-0.3 #-0.15
  phi_min: -0.9
  phi_max:  0.9 #0.8 #1.0 # 1.5
  linewidth_white: 0.05
  linewidth_yellow: 0.025
  lanewidth: 0.23
  sigma_d_mask: 0.7 #1.0
  sigma_phi_mask: 2.0 #2.0
  encoder_resolution: 135
  wheel_radius: 0.0318
  wheel_baseline: 0.1
